export const GOOGLE_SHEETS_CONFIG = {
    SHEET_ID: process.env.REACT_APP_GOOGLE_SHEET_ID,
    API_KEY: process.env.REACT_APP_GOOGLE_API_KEY,
    STUDENTS_RANGE: 'Students!A2:I1000',
    ORDERS_RANGE: 'Orders!A2:I1000'
  };